from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'smstart{CMD_INDEX}'
        self.MirrorCommand = f'sm{CMD_INDEX}'
        self.UnzipMirrorCommand = f'smunzismirror{CMD_INDEX}'
        self.ZipMirrorCommand = f'smzismirror{CMD_INDEX}'
        self.CancelMirror = f'smcancel{CMD_INDEX}'
        self.CancelAllCommand = f'smcancelall{CMD_INDEX}'
        self.ListCommand = f'smlist{CMD_INDEX}'
        self.SearchCommand = f'smsearch{CMD_INDEX}'
        self.StatusCommand = f'smstatus{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'smusers{CMD_INDEX}'
        self.AuthorizeCommand = f'smauthorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'smunauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'smaddsudo{CMD_INDEX}'
        self.RmSudoCommand = f'smrmsudo{CMD_INDEX}'
        self.PingCommand = f'smping{CMD_INDEX}'
        self.RestartCommand = f'smrestart{CMD_INDEX}'
        self.StatsCommand = f'smstats{CMD_INDEX}'
        self.HelpCommand = f'smhelp{CMD_INDEX}'
        self.LogCommand = f'smlog{CMD_INDEX}'
        self.SpeedCommand = f'smspeedtest{CMD_INDEX}'
        self.CloneCommand = f'smclone{CMD_INDEX}'
        self.CountCommand = f'smcount{CMD_INDEX}'
        self.WatchCommand = f'smwatch{CMD_INDEX}'
        self.ZipWatchCommand = f'smzipwatch{CMD_INDEX}'
        self.QbMirrorCommand = f'smqbmirror{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'smqbunzismirror{CMD_INDEX}'
        self.QbZipMirrorCommand = f'smqbzismirror{CMD_INDEX}'
        self.DeleteCommand = f'smdel{CMD_INDEX}'
        self.ShellCommand = f'smshell{CMD_INDEX}'
        self.ExecHelpCommand = f'smexechelp{CMD_INDEX}'
        self.LeechSetCommand = f'smleechset{CMD_INDEX}'
        self.SetThumbCommand = f'smsetthumb{CMD_INDEX}'
        self.LeechCommand = f'smleech{CMD_INDEX}'
        self.UnzipLeechCommand = f'smunzipleech{CMD_INDEX}'
        self.ZipLeechCommand = f'smzipleech{CMD_INDEX}'
        self.QbLeechCommand = f'smqbleech{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'smqbunzipleech{CMD_INDEX}'
        self.QbZipLeechCommand = f'smqbzipleech{CMD_INDEX}'
        self.LeechWatchCommand = f'smleechwatch{CMD_INDEX}'
        self.LeechZipWatchCommand = f'smleechzipwatch{CMD_INDEX}'
        self.RssListCommand = f'smrsslist{CMD_INDEX}'
        self.RssGetCommand = f'smrssget{CMD_INDEX}'
        self.RssSubCommand = f'smrsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'smrssunsub{CMD_INDEX}'
        self.RssUnSubAllCommand = f'smrssunsuball{CMD_INDEX}'
BotCommands = _BotCommands()
